// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v5.27.0
// source: converter_messages.proto

/* eslint-disable */

export const protobufPackage = "converter";

export interface HelloRequest {
  name: string;
}

export interface HelloReply {
  message: string;
}

export const CONVERTER_PACKAGE_NAME = "converter";
