// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v5.27.0
// source: converter_messages.proto

/* eslint-disable */

export const protobufPackage = "converter";

export interface FileUploadRequest {
  sourceFormat: string;
  targetFormat: string;
  fileName: string;
  chunk: Uint8Array;
}

export interface FileUploadResponse {
  fileName: string;
  chunk: Uint8Array;
}

export const CONVERTER_PACKAGE_NAME = "converter";
