services:
  frontend:
    build:
      context: ..
      dockerfile: ./docker/frontend.dockerfile
    restart: always
    ports:
      - "4200:4000"
  backend:
    build:
      context: ..
      dockerfile: ./docker/backend.dockerfile
    restart: always
    ports:
      - "3000:3000"
