version: '3.8'

services:
  # frontend:
  #   build:
  #     context: ..
  #     dockerfile: ./docker/frontend.dockerfile
  #   volumes:  # Fixed indentation here
  #     - "../client/apps/frontend:/app/apps/frontend"
  #     - "/app/node_modules"  # Fixed typo here
  #   ports:
  #     - "4200:4200"

  # backend:
  #   build:
  #     context: ..
  #     dockerfile: ./docker/backend.dockerfile
  #   volumes:
  #     - "../client/apps/backend:/app/client/apps/backend"
  #     - "/app/client/node_modules"  # Fixed typo here
  #   environment:
  #   - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
  #   - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
  #   - MINIO_PORT=${MINIO_PORT}
  #   - MINIO_HOST=${MINIO_HOST}
  #   - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
  #   ports:
  #     - "3000:3000"

  minio:
    image: minio/minio:RELEASE.2024-06-04T19-20-08Z
    command: server /data --console-address ":9001"

    volumes:
      - 'minio_data:/data'
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CMD_PORT}:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}

  db:
    image: postgres:16.3
    volumes:
      - convy_db:/var/lib/postgresql/data

    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DB}

volumes:
  minio_data:
  convy_db:
