version: '3.7'

services:
#   frontend:
#     build:
#       context: ..
#       dockerfile: ./docker/frontend.dockerfile
#     volumes:  # Fixed indentation here
#       - "../client:/app"
#       - "/app/node_modules"  # Fixed typo here
#     ports:
#       - "4200:4200"

  backend:
    build:
      context: ..
      dockerfile: ./docker/backend.dockerfile
    volumes:
      - "../client:/app/client"
      - "/app/client/node_modules"  # Fixed typo here
    ports:
      - "3000:3000"

#   minio:
#     image: minio/minio:RELEASE.2024-06-04T19-20-08Z
#     volumes:
#       - 'minio_data:/data'
#     environment:
#       - MINIO_ROOT_USER=${MINIO_ROOT_USER}
#       - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

# volumes:
#   minio_data:
#     driver: local
